### ISSUE TITLE
Weird behavior with the event effects

### ISSUE THREAD

**Issue by JesseFPV** [RotorHazard/LEDCtrlr#2] opened 2024-03-12 16:58 UTC
Last race I run the LedCtrl. I was setting the effects for the events as desired during the first few rounds.

Before I chanced effects it was working. After changing effects it looked like the LED was getting into some sort of bug state. The rainbow effect was glitchy (flickering very fast). 

When pressing Stop Effect on the LED control tab on Run page it went back to normal rainbow. It got back into the glitchy state after a new led event (lap enter/exit or another) was triggered.

I was not able to fix is during the race. The glitchy state was not too noticeable on FPV feed so I just led (😜) it be.

A wild guess: I felt like it was triggering the new effect on top of the old effect instead of replacing it (if this is possible at all).

I used the main branch uploaded last Wednesday.

**Comment by ethomas997** [comment] 2024-03-12 19:31
Thanks for the testing and posting, Jesse.  If possible, could you specify a series of steps that will reproduce the issue?

**Comment by ethomas997** [comment] 2024-03-21 06:53
Also if you can please generate a ".zip" file using the "Download Logs" button (in Settings | System) and post it here.

**Comment by ethomas997** [comment] 2024-03-24 07:59
I ran races today on a timer using the LEDCtrlr and after a couple of hours it got into that problematic state you describe.  Restarting the server brought it back to normal, so the issue seems to be there.  I've not yet been able to determine the root cause or an effective way to make it happen; I'll have to investigate.

**Comment by ethomas997** [comment] 2024-03-25 08:13
I've pushed a fix to the server 'main' branch that should address this issue. Let me know if you see it again with latest code.

Fixed by https://github.com/RotorHazard/RotorHazard/commit/60c52d4310c92bb1d20dcc22ba654e694bd71efd

**Closed as completed** 2024-03-25 08:13 UTC
Labels: bug
